name: Deploy Markdown Docs

on:
  push:
    branches:
      - main  # Trigger deployment when there's a push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get install -y curl
        curl -LO https://github.com/markedjs/marked/releases/download/v4.0.12/marked.min.js

    - name: Build static site
      run: |
        # You can run a build step here if needed (e.g., generating HTML files from Markdown)
        echo "Nothing to build. Static files are ready."

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages  # The branch to deploy to
        folder: .  # The folder containing the static files (usually the root)
        token: ${{ secrets.GITHUB_TOKEN }}
