# _config.yml

# Site settings
title: "PAL DOC Git Repo Transfer"
description: "Documentation for the Git repository transfer project."
url: "https://zacharia-pal.github.io"      # Your GitHub Pages domain
baseurl: "/DocLibPub/FPAL_DOC_GIT_repotransfer/PAL_DOC_GIT_repotransfer_EN"  # Repository path

# Markdown Processor
markdown: kramdown

# Theme configuration (you can change this to your preferred theme)
theme: jekyll-theme-minimal

# Include additional folders (e.g., assets)
include:
  - assets
